import type { FieldRole, FillableRole } from '../types';

/**
 * Expanded alias dictionary — Phase 1.1.
 * All aliases stored lowercase; matcher normalizes field signals the same way.
 */
export const FIELD_ALIASES: Record<FillableRole, string[]> = {
  business_name: [
    'business name',
    'company name',
    'company',
    'organization',
    'organisation',
    'business',
    'vendor',
    'listing name',
    'brand name',
    'brand',
    'site name',
    'website name',
    'org name',
    'trading name',
    'dba',
    'doing business as',
    'entity name',
    'business_name',
    'company_name',
    'companyname',
    'businessname',
    'org',
    'firm name',
    'agency name',
    'store name',
  ],
  title: [
    'title',
    'page title',
    'listing title',
    'headline',
    'subject',
    'post title',
    'entry title',
    'submission title',
    'article title',
    'job title',
    'position title',
  ],
  website: [
    'website',
    'homepage',
    'home page',
    'site',
    'url',
    'business url',
    'company url',
    'website url',
    'web site',
    'web address',
    'site url',
    'company website',
    'business website',
    'website_url',
    'websiteurl',
    'weburl',
    'link',
    'your website',
  ],
  email: [
    'email',
    'e mail',
    'e-mail',
    'email address',
    'e-mail address',
    'contact email',
    'business email',
    'work email',
    'email_address',
    'emailaddress',
    'mail',
    'your email',
  ],
  phone: [
    'phone',
    'telephone',
    'tel',
    'mobile',
    'phone number',
    'contact number',
    'cell',
    'cellphone',
    'phone_number',
    'phonenumber',
    'contact phone',
    'business phone',
    'mobile number',
    'fax',
  ],
  description: [
    'description',
    'about',
    'summary',
    'business description',
    'company description',
    'tell us about your business',
    'about us',
    'about your business',
    'about your company',
    'bio',
    'details',
    'long description',
    'short description',
    'overview',
    'desc',
    'company overview',
    'business overview',
    'what do you do',
    'tell us about',
  ],
  address: [
    'address',
    'street address',
    'street',
    'address line',
    'address line 1',
    'address1',
    'addr',
    'mailing address',
    'business address',
    'street address 1',
    'address line1',
  ],
  city: ['city', 'town', 'locality', 'municipality', 'city town'],
  state: [
    'state',
    'province',
    'region',
    'state province',
    'state/province',
    'county',
    'prefecture',
  ],
  country: ['country', 'nation', 'country region', 'country/region'],
  zip: [
    'zip',
    'zip code',
    'zipcode',
    'postal',
    'postal code',
    'postcode',
    'post code',
    'pin',
    'pin code',
    'pincode',
  ],
  category: [
    'category',
    'categories',
    'business category',
    'industry',
    'niche',
    'type',
    'business type',
    'listing category',
    'directory category',
    'select category',
    'choose category',
    'primary category',
    'classification',
    'sector',
  ],
  facebook: [
    'facebook',
    'facebook url',
    'facebook page',
    'fb',
    'fb url',
    'facebook_url',
    'facebook profile',
  ],
  linkedin: [
    'linkedin',
    'linked in',
    'linkedin url',
    'linkedin page',
    'linkedin profile',
    'linkedin_url',
  ],
  twitter: [
    'twitter',
    'twitter url',
    'twitter handle',
    'x',
    'x url',
    'x com',
    'twitter_url',
    'tweet',
    'x profile',
  ],
};

export const ROLE_LABELS: Record<FieldRole, string> = {
  business_name: 'Business Name',
  title: 'Title',
  website: 'Website',
  email: 'Email',
  phone: 'Phone',
  description: 'Description',
  address: 'Address',
  city: 'City',
  state: 'State',
  country: 'Country',
  zip: 'ZIP',
  category: 'Category',
  facebook: 'Facebook',
  linkedin: 'LinkedIn',
  twitter: 'Twitter',
  captcha: 'CAPTCHA',
  payment: 'Payment',
  submit: 'Submit',
  login: 'Login',
  search: 'Search',
  newsletter: 'Newsletter',
  unknown: 'Unknown',
};

/** Structural / keyword hints for non-fillable roles (not alias-scored the same way) */
export const STRUCTURAL_HINTS: Record<
  'captcha' | 'payment' | 'submit' | 'login' | 'search' | 'newsletter',
  string[]
> = {
  captcha: [
    'captcha',
    'recaptcha',
    'hcaptcha',
    'turnstile',
    'i am not a robot',
    'security check',
    'verify you are human',
  ],
  payment: [
    'credit card',
    'card number',
    'cardnumber',
    'cvv',
    'cvc',
    'expiry',
    'expiration',
    'billing',
    'payment method',
    'pay with',
    'pricing plan',
    'price plan',
    'subscription',
    'iban',
    'routing number',
    'paypal',
    'stripe',
    'mastercard',
    'visa',
    'amex',
    'monthly fee',
    'annual fee',
    'paid plan',
    'premium plan',
    'free plan',
    'choose a plan',
    'select plan',
    'payment',
  ],
  submit: ['submit', 'send', 'publish', 'post listing', 'create listing', 'finish', 'complete registration'],
  login: [
    'password',
    'passwd',
    'username',
    'user name',
    'sign in',
    'signin',
    'log in',
    'login',
    'otp',
    'one time',
    'verification code',
    '2fa',
    'mfa',
  ],
  search: ['search', 'query', 'find', 'filter', 'keyword search', 'site search'],
  newsletter: ['newsletter', 'subscribe', 'mailing list', 'promo code', 'coupon', 'discount code'],
};
