import type {
  ExecutiveSummaryBlock,
  GeneratedReportDocument,
  ReportBrandConfig,
  ReportSection,
  ReportType,
} from './types.js';
import { REPORT_TYPE_META } from './types.js';

const DEFAULT_BRAND: ReportBrandConfig = {
  name: 'SEO OS',
  primaryColor: '#0d9488',
  secondaryColor: '#0369a1',
  footerText: 'Confidential — generated by SEO OS Reports Engine',
  coverTitle: 'Executive Intelligence Report',
  agencyName: 'SEO OS',
};

export function generateExecutiveSummary(input: {
  reportType: ReportType;
  metrics: Record<string, number>;
  insights?: Array<{ title: string; body?: string; recommendation?: string; severity?: string }>;
}): ExecutiveSummaryBlock {
  const m = input.metrics;
  const wins: string[] = [];
  const risks: string[] = [];
  const recs: string[] = [];
  const next: string[] = [];
  const growth: string[] = [];
  const highlights: string[] = [];

  if ((m.backlinksWon ?? 0) > 0) {
    wins.push(`Secured ${m.backlinksWon} won backlinks this period.`);
    highlights.push(`${m.backlinksWon} backlinks won`);
  }
  if ((m.campaignSuccessRate ?? 0) >= 60) {
    wins.push(`Campaign success rate reached ${m.campaignSuccessRate}%.`);
    highlights.push(`${m.campaignSuccessRate}% campaign success`);
  }
  if ((m.replyRate ?? 0) > 0) {
    highlights.push(`${m.replyRate}% outreach reply rate`);
  }
  if ((m.aiHoursSaved ?? 0) > 0) {
    wins.push(`AI workforce saved approximately ${m.aiHoursSaved} hours.`);
    highlights.push(`${m.aiHoursSaved} AI hours saved`);
  }
  if ((m.workflowSuccessRate ?? 0) >= 80) {
    wins.push(`Workflows running at ${m.workflowSuccessRate}% success.`);
  } else if ((m.workflowSuccessRate ?? 0) > 0 && (m.workflowSuccessRate ?? 0) < 60) {
    risks.push(`Workflow success is only ${m.workflowSuccessRate}% — review failed runs.`);
  }
  if ((m.replyRate ?? 0) > 0 && (m.replyRate ?? 0) < 10) {
    risks.push('Outreach reply rate is below healthy benchmarks.');
    recs.push('Refresh subject lines and tighten prospect qualification.');
  }
  if ((m.relationshipHealth ?? 0) < 50 && (m.relationshipHealth ?? 0) > 0) {
    risks.push('Average relationship health is soft — prioritize warm follow-ups.');
  }

  for (const ins of input.insights ?? []) {
    if (ins.severity === 'warning' || ins.severity === 'critical') {
      risks.push(ins.title);
    } else {
      highlights.push(ins.title);
    }
    if (ins.recommendation) recs.push(ins.recommendation);
  }

  if (!recs.length) {
    recs.push('Scale winning campaign templates into adjacent niches.');
    recs.push('Enable more event-triggered workflows for scan → outreach.');
  }
  next.push('Approve pending outreach drafts this week.');
  next.push('Verify newly won backlinks and update relationship scores.');
  next.push('Share this report with stakeholders and lock next-period goals.');

  growth.push(
    `Projected backlink growth supports continued compounding authority.`
  );
  growth.push(
    `AI productivity is expected to rise as workflow coverage expands.`
  );
  if ((m.roiIndex ?? 0) > 0) {
    growth.push(`ROI index currently ${m.roiIndex} with upward 30/90-day forecast.`);
  }

  if (!highlights.length) {
    highlights.push('Platform activity captured across SEO, campaigns, and automation.');
  }
  if (!wins.length) {
    wins.push('Foundation metrics established for ongoing executive reporting.');
  }

  const meta = REPORT_TYPE_META[input.reportType];
  const narrative = `${meta.label}: ${highlights.slice(0, 3).join('; ')}. ${
    wins[0] ?? ''
  } Recommended focus: ${recs[0] ?? 'sustain current momentum.'}`;

  return {
    highlights: unique(highlights).slice(0, 6),
    keyWins: unique(wins).slice(0, 5),
    risks: unique(risks).slice(0, 5),
    recommendations: unique(recs).slice(0, 5),
    nextActions: unique(next).slice(0, 5),
    projectedGrowth: unique(growth).slice(0, 4),
    narrative,
  };
}

export function buildReportDocument(input: {
  reportType: ReportType;
  title?: string;
  brand?: Partial<ReportBrandConfig>;
  metrics: Record<string, number>;
  insights?: Array<{ title: string; body?: string; recommendation?: string; severity?: string }>;
  forecasts?: Array<{
    metric: string;
    current: number;
    projected30d: number;
    projected90d: number;
  }>;
  periodLabel?: string;
}): GeneratedReportDocument {
  const brand: ReportBrandConfig = { ...DEFAULT_BRAND, ...input.brand };
  const executiveSummary = generateExecutiveSummary({
    reportType: input.reportType,
    metrics: input.metrics,
    insights: input.insights,
  });
  const sections = buildSections(input.reportType, input.metrics, executiveSummary);
  const meta = REPORT_TYPE_META[input.reportType];

  return {
    reportType: input.reportType,
    title: input.title || meta.label,
    generatedAt: new Date().toISOString(),
    periodLabel: input.periodLabel ?? 'Current period',
    brand,
    executiveSummary,
    sections,
    metrics: input.metrics,
    insights: (input.insights ?? []).map((i) => ({
      title: i.title,
      body: i.body ?? '',
      severity: i.severity,
    })),
    forecasts: input.forecasts ?? [],
  };
}

function buildSections(
  type: ReportType,
  metrics: Record<string, number>,
  summary: ExecutiveSummaryBlock
): ReportSection[] {
  const sections: ReportSection[] = [
    {
      id: 'exec',
      title: 'Executive Summary',
      body: summary.narrative,
      metrics: {
        highlights: summary.highlights.length,
        risks: summary.risks.length,
      },
    },
  ];

  const addPerf = (title: string, keys: string[], chartHint: ReportSection['chartHint']) => {
    sections.push({
      id: title.toLowerCase().replace(/\s+/g, '_'),
      title,
      body: `${title} snapshot for this reporting period.`,
      chartHint,
      rows: keys
        .filter((k) => metrics[k] != null)
        .map((k) => ({ label: k, value: metrics[k]! })),
      metrics: Object.fromEntries(keys.filter((k) => metrics[k] != null).map((k) => [k, metrics[k]!])),
    });
  };

  switch (type) {
    case 'backlink':
      addPerf('Backlink Performance', ['backlinksWon', 'backlinksVerified', 'backlinkSuccessRate', 'avgAuthority'], 'funnel');
      break;
    case 'campaign':
      addPerf('Campaign Performance', ['campaignSuccessRate', 'campaignsActive', 'approvalRate', 'estimatedRoi'], 'bar');
      break;
    case 'outreach':
      addPerf('Outreach Performance', ['emailsSent', 'openRate', 'replyRate', 'conversionRate'], 'line');
      break;
    case 'workflow':
      addPerf('Workflow Performance', ['workflowsExecuted', 'workflowSuccessRate', 'automationHoursSaved'], 'area');
      break;
    case 'ai_productivity':
      addPerf('AI Productivity', ['aiTasksCompleted', 'aiHoursSaved', 'tokensUsed', 'agentUtilization'], 'leaderboard');
      break;
    case 'organization_summary':
      addPerf('Relationship Health', ['relationships', 'relationshipHealth', 'relationshipsImproved'], 'donut');
      break;
    case 'client_seo':
      addPerf('SEO Performance', ['keywords', 'opportunities', 'prospects', 'pagesAnalyzed'], 'area');
      addPerf(
        'Technical SEO Health',
        [
          'technicalHealthScore',
          'pagesAudited',
          'criticalSeoIssues',
          'highSeoIssues',
          'issueResolutionRate',
          'averageFixMinutes',
        ],
        'donut'
      );
      break;
    default:
      addPerf(
        'Portfolio Snapshot',
        [
          'backlinksWon',
          'campaignSuccessRate',
          'replyRate',
          'workflowSuccessRate',
          'aiHoursSaved',
          'roiIndex',
        ],
        'bar'
      );
      addPerf(
        'Technical SEO Health',
        ['technicalHealthScore', 'pagesAudited', 'criticalSeoIssues', 'issueResolutionRate'],
        'area'
      );
  }

  sections.push({
    id: 'recommendations',
    title: 'Recommended Next Steps',
    body: summary.recommendations.join(' '),
    rows: summary.nextActions.map((a, i) => ({ label: `Action ${i + 1}`, value: a })),
  });

  sections.push({
    id: 'outlook',
    title: 'Growth Outlook',
    body: summary.projectedGrowth.join(' '),
    chartHint: 'line',
  });

  return sections;
}

function unique(items: string[]) {
  return [...new Set(items.filter(Boolean))];
}

export function computeNextRunAt(schedule: string, from = new Date()): Date | null {
  const d = new Date(from);
  switch (schedule) {
    case 'weekly':
      d.setDate(d.getDate() + 7);
      return d;
    case 'monthly':
      d.setMonth(d.getMonth() + 1);
      return d;
    case 'quarterly':
      d.setMonth(d.getMonth() + 3);
      return d;
    default:
      return null;
  }
}

export function flattenReportForCsv(doc: GeneratedReportDocument): string[][] {
  const rows: string[][] = [
    ['field', 'value'],
    ['title', doc.title],
    ['reportType', doc.reportType],
    ['period', doc.periodLabel],
    ['generatedAt', doc.generatedAt],
  ];
  for (const [k, v] of Object.entries(doc.metrics)) {
    rows.push([`metric.${k}`, String(v)]);
  }
  doc.executiveSummary.highlights.forEach((h, i) => rows.push([`highlight.${i + 1}`, h]));
  doc.executiveSummary.recommendations.forEach((h, i) =>
    rows.push([`recommendation.${i + 1}`, h])
  );
  return rows;
}

export function reportToPlainText(doc: GeneratedReportDocument): string {
  const lines = [
    doc.brand.coverTitle || doc.title,
    doc.brand.agencyName || '',
    `Period: ${doc.periodLabel}`,
    `Generated: ${doc.generatedAt}`,
    '',
    'EXECUTIVE SUMMARY',
    doc.executiveSummary.narrative,
    '',
    'HIGHLIGHTS',
    ...doc.executiveSummary.highlights.map((h) => `• ${h}`),
    '',
    'KEY WINS',
    ...doc.executiveSummary.keyWins.map((h) => `• ${h}`),
    '',
    'RISKS',
    ...doc.executiveSummary.risks.map((h) => `• ${h}`),
    '',
    'RECOMMENDATIONS',
    ...doc.executiveSummary.recommendations.map((h) => `• ${h}`),
    '',
    'NEXT ACTIONS',
    ...doc.executiveSummary.nextActions.map((h) => `• ${h}`),
    '',
    'PROJECTED GROWTH',
    ...doc.executiveSummary.projectedGrowth.map((h) => `• ${h}`),
    '',
  ];
  for (const s of doc.sections) {
    lines.push(s.title.toUpperCase(), s.body, '');
    if (s.rows) {
      for (const r of s.rows) lines.push(`  - ${r.label}: ${r.value}`);
      lines.push('');
    }
  }
  if (doc.brand.footerText) lines.push(doc.brand.footerText);
  return lines.join('\n');
}
