export interface WorkflowStep {
  id: string;
  number: number;
  emoji: string;
  title: string;
  purpose: string;
  aiTip?: string;
  route: string;
  /** Route is org-level (not under /projects/:id) */
  orgLevel?: boolean;
  estimatedMinutes?: number;
  difficulty?: 'Beginner' | 'Easy' | 'Intermediate';
}

export const WORKFLOW_STEPS: WorkflowStep[] = [
  {
    id: 'create-org',
    number: 1,
    emoji: '🏢',
    title: 'Create Organization',
    purpose: 'Create the company or client workspace that separates users, projects, and AI memory.',
    route: '/onboarding/organization',
    orgLevel: true,
    estimatedMinutes: 2,
    difficulty: 'Beginner',
  },
  {
    id: 'create-project',
    number: 2,
    emoji: '📁',
    title: 'Create Project',
    purpose: 'Create one project per website — your central workspace for all SEO activities.',
    aiTip: 'This project becomes the central workspace for all SEO activities.',
    route: '/onboarding/project',
    orgLevel: true,
    estimatedMinutes: 3,
    difficulty: 'Beginner',
  },
  {
    id: 'analyze-website',
    number: 3,
    emoji: '🌐',
    title: 'Analyze Website',
    purpose: 'Run Browser Intelligence to discover pages, metadata, schema, tech stack, and opportunities.',
    route: 'intelligence/browser',
    estimatedMinutes: 5,
    difficulty: 'Easy',
  },
  {
    id: 'knowledge-base',
    number: 4,
    emoji: '📚',
    title: 'Build Knowledge Base',
    purpose: 'Upload brand documents so AI understands your business and generates better content.',
    aiTip: 'This information helps AI understand your business and generate better content.',
    route: 'knowledge/library',
    estimatedMinutes: 5,
    difficulty: 'Easy',
  },
  {
    id: 'ai-memory',
    number: 5,
    emoji: '🧠',
    title: 'AI Memory',
    purpose: 'Store business summary, brand voice, goals, audience, and USPs for consistent AI output.',
    route: 'memory/timeline',
    estimatedMinutes: 4,
    difficulty: 'Easy',
  },
  {
    id: 'seo-audit',
    number: 6,
    emoji: '🔍',
    title: 'Website SEO Audit',
    purpose: 'Analyze titles, descriptions, headings, speed, broken links, and accessibility.',
    route: 'backlink-builder/audit',
    estimatedMinutes: 5,
    difficulty: 'Easy',
  },
  {
    id: 'competitors',
    number: 7,
    emoji: '🏆',
    title: 'Competitor Intelligence',
    purpose: 'Discover and analyze competitor SEO, content, backlinks, and keyword gaps.',
    route: 'competitors',
    estimatedMinutes: 5,
    difficulty: 'Intermediate',
  },
  {
    id: 'keywords',
    number: 8,
    emoji: '🎯',
    title: 'Keyword Intelligence',
    purpose: 'Generate primary, secondary, long-tail, and local keywords with search intent.',
    route: 'intelligence/keywords',
    estimatedMinutes: 5,
    difficulty: 'Intermediate',
  },
  {
    id: 'import-websites',
    number: 9,
    emoji: '🔗',
    title: 'Import Target Websites',
    purpose: 'Import CSV, Excel, or manual URLs as backlink opportunities.',
    route: 'backlink-builder/import',
    estimatedMinutes: 3,
    difficulty: 'Easy',
  },
  {
    id: 'ai-analysis',
    number: 10,
    emoji: '🤖',
    title: 'AI Website Analysis',
    purpose: 'Validate URLs, classify opportunity types, and score relevance, authority, and priority.',
    route: 'backlink-builder/automation',
    estimatedMinutes: 8,
    difficulty: 'Intermediate',
  },
  {
    id: 'content-generator',
    number: 11,
    emoji: '✍️',
    title: 'AI Content Generator',
    purpose: 'Generate guest posts, emails, directory copy, and outreach drafts for approval.',
    route: 'outreach/studio',
    estimatedMinutes: 6,
    difficulty: 'Easy',
  },
  {
    id: 'campaign-builder',
    number: 12,
    emoji: '📢',
    title: 'Campaign Builder',
    purpose: 'Group opportunities, assign priority, owners, timeline, and campaign goals.',
    route: 'campaigns',
    estimatedMinutes: 5,
    difficulty: 'Intermediate',
  },
  {
    id: 'relationships',
    number: 13,
    emoji: '🤝',
    title: 'Relationship Intelligence',
    purpose: 'Discover organizations, editors, contacts, and relationship health over time.',
    route: 'relationships',
    estimatedMinutes: 5,
    difficulty: 'Intermediate',
  },
  {
    id: 'outreach',
    number: 14,
    emoji: '📨',
    title: 'Outreach',
    purpose: 'Send personalized emails, track opens, replies, and negotiation through to won/lost.',
    route: 'outreach/inbox',
    estimatedMinutes: 10,
    difficulty: 'Intermediate',
  },
  {
    id: 'verification',
    number: 15,
    emoji: '✅',
    title: 'Backlink Verification',
    purpose: 'Verify backlinks exist, anchor text, dofollow status, and indexing.',
    route: 'backlink-builder/pending',
    estimatedMinutes: 4,
    difficulty: 'Easy',
  },
  {
    id: 'reports',
    number: 16,
    emoji: '📈',
    title: 'Reports',
    purpose: 'Generate SEO, campaign, backlink, and executive reports.',
    route: 'reports/library',
    estimatedMinutes: 3,
    difficulty: 'Easy',
  },
  {
    id: 'mission-control',
    number: 17,
    emoji: '🎯',
    title: 'Mission Control',
    purpose: 'View website health, knowledge score, backlink progress, and AI workforce activity.',
    route: 'mission-control',
    estimatedMinutes: 2,
    difficulty: 'Beginner',
  },
];

export const TOTAL_WORKFLOW_STEPS = WORKFLOW_STEPS.length;
